from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from datetime import datetime
from io import BytesIO

RISK_COLORS = {
    "low": HexColor("#166534"),
    "medium": HexColor("#854d0e"),
    "high": HexColor("#991b1b"),
}

GREEN = HexColor("#14532d")
GRAY = HexColor("#6b7280")
LIGHT_GRAY = HexColor("#e5e7eb")


def generate_report_pdf(loan: dict, score: dict, climate: dict, watermark: bool = False) -> bytes:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    x_margin = 20 * mm
    y = height - 25 * mm

    if watermark:
        c.saveState()
        c.setFont("Helvetica-Bold", 60)
        c.setFillColor(HexColor("#f0fdf4"))
        c.translate(width / 2, height / 2)
        c.rotate(45)
        c.drawCentredString(0, 0, "DEMO — SAMPLE ONLY")
        c.restoreState()

    # Title
    c.setFillColor(GREEN)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(x_margin, y, "Green Taxonomy Loan Risk Report")
    y -= 8 * mm

    c.setFillColor(GRAY)
    c.setFont("Helvetica", 9)
    c.drawString(x_margin, y, f"Generated {datetime.now().strftime('%d %B %Y, %H:%M')}")
    y -= 12 * mm

    # Risk badge
    risk_color = RISK_COLORS.get(score["riskLevel"], GRAY)
    c.setFillColor(risk_color)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y, f"{score['riskLevel'].upper()} RISK")

    green_label = "GREEN-ALIGNED" if score["isGreen"] else "NOT GREEN-ALIGNED"
    c.setFillColor(GREEN if score["isGreen"] else GRAY)
    c.drawString(x_margin + 60 * mm, y, green_label)
    y -= 14 * mm

    # Loan details section
    y = _section_header(c, "Loan Details", x_margin, y)
    rows = [
        ("Amount", f"{loan.get('currency', 'KES')} {loan['loanAmount']:,.0f}"),
        ("Purpose", loan["purpose"]),
        ("Sector", loan["sector"].title()),
        ("County", loan["county"]),
    ]
    if loan.get("description"):
        rows.append(("Details", loan["description"]))
    y = _table(c, rows, x_margin, y, width - 2 * x_margin)
    y -= 8 * mm

    # Scoring explanation
    y = _section_header(c, "Scoring Explanation", x_margin, y)
    y = _wrapped_text(c, score["explanation"], x_margin, y, width - 2 * x_margin)
    y -= 4 * mm
    c.setFillColor(GRAY)
    c.setFont("Helvetica", 9)
    c.drawString(x_margin, y, "Confidence")
    y -= 5 * mm
    c.setFillColor(HexColor("#1a1a1a"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y, f"{score['confidence'] * 100:.0f}%")
    y -= 12 * mm

    # Climate signal
    y = _section_header(c, "Climate Signal (Live)", x_margin, y)
    status = climate.get("status", "unknown").replace("_", " ").title()
    climate_line = f"Status: {status}"
    if climate.get("anomaly_pct") is not None:
        climate_line += f"  ·  {climate['anomaly_pct']:+.1f}% rainfall anomaly (30-day)"
    y = _wrapped_text(c, climate_line, x_margin, y, width - 2 * x_margin)
    y -= 14 * mm

    # Footer
    c.setStrokeColor(LIGHT_GRAY)
    c.line(x_margin, y, width - x_margin, y)
    y -= 6 * mm
    c.setFillColor(GRAY)
    c.setFont("Helvetica", 7)
    footer_text = (
        "Generated by Green Taxonomy Risk Scorer. Scoring based on Kenya's Green Finance "
        "Taxonomy (KGFT) sector rules and live rainfall data. This report is a decision-support "
        "tool and does not replace formal compliance review."
    )
    y = _wrapped_text(c, footer_text, x_margin, y, width - 2 * x_margin, font_size=7, leading=10)

    c.save()
    buffer.seek(0)
    return buffer.getvalue()


def _section_header(c, text, x, y):
    c.setFillColor(HexColor("#1a1a1a"))
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, text)
    return y - 7 * mm


def _table(c, rows, x, y, max_width):
    c.setFont("Helvetica", 10)
    for label, value in rows:
        c.setFillColor(GRAY)
        c.drawString(x, y, label)
        c.setFillColor(HexColor("#1a1a1a"))
        c.drawString(x + 45 * mm, y, str(value))
        y -= 6 * mm
    return y


def _wrapped_text(c, text, x, y, max_width, font_size=10, leading=13):
    c.setFont("Helvetica", font_size)
    c.setFillColor(HexColor("#1a1a1a") if font_size > 7 else GRAY)
    words = text.split()
    line = ""
    for word in words:
        test_line = f"{line} {word}".strip()
        if c.stringWidth(test_line, "Helvetica", font_size) > max_width:
            c.drawString(x, y, line)
            y -= leading
            line = word
        else:
            line = test_line
    if line:
        c.drawString(x, y, line)
        y -= leading
    return y